### ISSUE TITLE
Error running sample java output plugin 

### ISSUE THREAD

**Issue by michaelhyatt** [logstash-plugins/logstash-output-java_output_example#3]
Following instructions to run the sample plugin word for word, as per https://www.elastic.co/guide/en/logstash/current/java-output-plugin.html

Running the last command with sample flow after successfully installing the sample plugin:
bin/logstash --java-execution -f /path/to/java_output.conf

Getting the following error:
[2019-04-09T22:18:29,823][ERROR][logstash.plugins.registry] Tried to load a plugin's code, but failed. {:exception=>#<LoadError: no such file to load -- logstash-output-java_output_example_jars>, :path=>"logstash/outputs/java_output_example", :type=>"output", :name=>"java_output_example"}
[2019-04-09T22:18:29,836][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any output plugin named 'java_output_example'. Are you sure this is correct? Trying to load the java_output_example output plugin resulted in this error: no such file to load -- logstash-output-java_output_example_jars", :backtrace=>["/Users/mcm/work/elastic/logstash-6.7.0/logstash-core/lib/logstash/plugins/registry.rb:211:in `lookup_pipeline_plugin'", "/Users/mcm/work/elastic/logstash-6.7.0/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:200:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:137:in `buildOutput'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "/Users/mcm/work/elastic/logstash-6.7.0/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", "/Users/mcm/work/elastic/logstash-6.7.0/logstash-core/lib/logstash/pipeline_action/create.rb:37:in `execute'", "/Users/mcm/work/elastic/logstash-6.7.0/logstash-core/lib/logstash/agent.rb:334:in `block in converge_state'"]}

**Comment by danhermann** [comment]
@michaelhyatt, thank you for trying the new Java API. There was a missing Ruby source file (these Ruby source files will be auto-generated in the GA release of Java plugins) in this example that I committed in https://github.com/logstash-plugins/logstash-output-java_output_example/commit/8734eb7b1d78e677773607b9db7bdfdbb579690f that should resolve your problem. After pulling that file, you should have to repeat only the `gem build` and following steps to get this output plugin running. Apologies for your trouble and let us know if you encounter any other problems.

**Comment by jcr-dev** [comment]
I was not even able to get as far as installing the plugin, I see errors when following the directions to even build the output plugin 

Could not find method register() for arguments [downloadJRuby, class de.undercouch.gradle.tasks.download.Download, rubyUtils_23g3p0nntt4rcy9rs6o9yrnra$_run_closure2@2a8df438] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.
